In [1]:
from backtest import get_df, get_hma, tradingStrategy, get_params_lines, CommInfoFractional, plot
import pandas as pd
import backtrader as bt

In [2]:
price_df = get_df('BTC-PERP')

In [3]:
price_df['price_hall'] = get_hma(price_df['close'], 30)
price_df['volatility'] = (price_df['close'].std()/price_df['close']) * 100

In [4]:
initial_cash = 1000
mult = 1
params = {'stop': 800}
pair = 'BTC-PERP'

In [5]:
PandasData_Custom = get_params_lines(price_df.columns)

In [6]:
price_data = PandasData_Custom(dataname=price_df)

cerebro = bt.Cerebro()

cerebro.adddata(price_data, name='data')
cerebro.addstrategy(tradingStrategy, parameters=params)
cerebro.addanalyzer(bt.analyzers.SharpeRatio, riskfreerate=0.0, annualize=True, timeframe=bt.TimeFrame.Days)
cerebro.addanalyzer(bt.analyzers.TradeAnalyzer)

cerebro.broker = bt.brokers.BackBroker(cash=initial_cash, slip_perc=0.01/100, commission = CommInfoFractional(commission=(0.075*mult)/100, mult=mult), slip_open=True, slip_out=True)  # 0.5%
run = cerebro.run()

In [7]:
portfolio, trades, operations, stops_triggered = run[0].get_logs()

In [8]:
portfolio

          Date        Value
0   2019-07-20  1000.000000
1   2019-07-21  1000.000000
2   2019-07-22  1000.000000
3   2019-07-23  1000.000000
4   2019-07-24  1000.000000
..         ...          ...
820 2021-10-17   779.487702
821 2021-10-18   779.487702
822 2021-10-19   779.487702
823 2021-10-20   779.487702
824 2021-10-21   779.487702

[825 rows x 2 columns]

In [9]:
trades

         Date  Type         Price  Total Spent  Comission
0  2019-09-04   BUY  10638.813775   999.217314   0.749413
1  2019-09-18  SELL  10194.730425   999.217314   0.718131
2  2019-10-10   BUY   8588.108725   955.962079   0.716972
3  2019-10-19  SELL   7953.204600   955.962079   0.663967
4  2019-10-22   BUY   8207.320650   883.569610   0.662677
5  2019-10-23  SELL   8021.947725   883.569610   0.647710
6  2019-10-27   BUY   9264.926400   862.725558   0.647044
7  2019-11-09  SELL   8770.622850   862.725558   0.612523
8  2019-12-04   BUY   7296.979625   815.480309   0.611610
9  2019-12-05  SELL   7190.280900   815.480309   0.602667
10 2019-12-06   BUY   7393.989325   802.299390   0.601725
11 2019-12-13  SELL   7187.531175   802.299390   0.584923

In [10]:
plot(price_df, portfolio, pair)